# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PiroPay
email: info@piropay.com
description: > # this means to ignore newlines until "baseurl:"
  Accept your customer payments easily, on mostly all devices, worldwide using PiroPay. Simplify accepting payments management with Piropay's fully customizable, integrated payments solution.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://piropay.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: Piropay
github_username:  Piropay
facebook_username: Piropay
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: 
#skype_username: Piropay
linkedin_url: https://

# Address information
address_street: B 29 Harley Street
address_city: London
address_state: England
address_zip: W1G 2QR
address_country: UK

# Build settings
markdown: kramdown
